name: calendar_timeline
description: Flutter widget form select a date in horizontal timeline. You can select month and day easily.
version: 0.2.0
homepage: https://github.com/ikicodedev/calendar_timeline

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.1.4
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
